"""
PlatformIO pre-build script: compresses CAM_PAGE_HTML into a gzip byte array.
Generates  include/cam_page_gz.h  with:
  - const uint8_t  CAM_PAGE_GZ[]    (PROGMEM, gzip data)
  - const uint32_t CAM_PAGE_GZ_LEN  (byte count)
  - const char*    CAM_PAGE_RAW     (kept for token injection marker search)

Run automatically via  extra_scripts = pre:scripts/gzip_html.py  in platformio.ini.
"""

Import("env")  # PlatformIO SCons binding

import gzip, re, os, pathlib

SRC = pathlib.Path("lib", "audio_stream_handler.h")
DST = pathlib.Path("include", "cam_page_gz.h")

def gzip_html(source, target, env):
    # 1. Extract raw HTML from R"CAMPAGE(...)CAMPAGE"
    text = SRC.read_text(encoding="utf-8")
    m = re.search(r'R"CAMPAGE\((.*?)\)CAMPAGE"', text, re.DOTALL)
    if not m:
        print("[gzip_html] WARNING: CAMPAGE block not found - skipping")
        return
    html = m.group(1)
    raw_len = len(html.encode("utf-8"))

    # 2. Gzip compress (max level)
    gz = gzip.compress(html.encode("utf-8"), compresslevel=9)
    gz_len = len(gz)

    # 3. Generate C header
    hex_lines = []
    for i in range(0, gz_len, 16):
        chunk = gz[i:i+16]
        hex_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    hex_body = ",\n".join(hex_lines)

    header = f"""// AUTO-GENERATED by scripts/gzip_html.py - do not edit
// Raw HTML: {raw_len:,} bytes -> Gzip: {gz_len:,} bytes ({100*gz_len/raw_len:.1f}%)
#pragma once
#include <pgmspace.h>
#include <stdint.h>

static const uint8_t CAM_PAGE_GZ[] PROGMEM = {{
{hex_body}
}};
static const uint32_t CAM_PAGE_GZ_LEN = {gz_len};
"""
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text(header, encoding="utf-8")
    print(f"[gzip_html] {raw_len:,} -> {gz_len:,} bytes ({100*(raw_len-gz_len)/raw_len:.1f}% saved) -> {DST}")

# Register as pre-build action
env.AddPreAction("buildprog", env.Action(gzip_html, "[gzip_html] Compressing CAM_PAGE_HTML"))
